<?php
 /*
 * Template Name: PaymentForm
 * Custom template used for custom php code display
 * @package   Portafolio WordPress Theme
 * @author    Gufran Hasan
 * @copyright Copyright templatecustom.com
 * @link      http://www.templatecustom.com
 */
?>
<?php get_header(); ?>
<?php
  //write code here

echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<script src="https://unpkg.com/imask"></script>';
echo '<script src="/dateFormat.js"></script>';
echo '<script src="https://unpkg.com/axios/dist/axios.min.js"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"';
echo 'integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>';
echo '<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">';
echo '<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>';
echo '<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '</head>';
echo '';
echo '<body>';
echo '<style>';
echo '.box select {';
echo 'background-color: #fff;';
echo 'color: rgb(36, 36, 36);';
echo 'padding: 12px;';
echo 'width: 100%;';
echo 'border: none;';
echo 'font-size: 20px;';
echo 'box-shadow: 0 5px 25px rgba(0, 0, 0, 0.2);';
echo '-webkit-appearance: button;';
echo 'appearance: button;';
echo 'outline: none;';
echo '';
echo 'padding: 0.6em 0.25em 0;';
echo 'font-size: 1.5em;';
echo 'height: 2.1em;';
echo 'margin-bottom: 0.25em;';
echo 'border: none;';
echo 'border-bottom: 1px solid peachpuff;';
echo 'font-family: Raleway, Helvetica, sans-serif;';
echo 'font-weight: 100;';
echo 'border-radius: 0.25em;';
echo '}';
echo '';
echo '.box::before {';
echo 'content: "\f13a";';
echo 'font-family: FontAwesome;';
echo 'position: absolute;';
echo 'top: 0;';
echo 'right: 0;';
echo 'width: 20%;';
echo 'height: 100%;';
echo 'text-align: center;';
echo 'font-size: 28px;';
echo 'line-height: 45px;';
echo 'color: rgba(255, 255, 255, 0.5);';
echo 'background-color: rgba(255, 255, 255, 0.1);';
echo 'pointer-events: none;';
echo '}';
echo '';
echo '.box:hover::before {';
echo 'color: rgba(255, 255, 255, 0.6);';
echo 'background-color: rgba(255, 255, 255, 0.2);';
echo '}';
echo '';
echo '.box select option {';
echo 'padding: 30px;';
echo '}';
echo '';
echo '/* The snackbar - position it at the bottom and in the middle of the screen */';
echo '#snackbar {';
echo 'visibility: hidden;';
echo '/* Hidden by default. Visible on click */';
echo 'min-width: 250px;';
echo '/* Set a default minimum width */';
echo 'margin-left: -125px;';
echo '/* Divide value of min-width by 2 */';
echo 'background-color: rgb(155, 0, 0);';
echo '/* Black background color */';
echo 'color: #fff;';
echo '/* White text color */';
echo 'text-align: center;';
echo '/* Centered text */';
echo 'border-radius: 2px;';
echo '/* Rounded borders */';
echo 'padding: 16px;';
echo '/* Padding */';
echo 'position: fixed;';
echo '/* Sit on top of the screen */';
echo 'z-index: 1;';
echo '/* Add a z-index if needed */';
echo 'left: 50%;';
echo '/* Center the snackbar */';
echo 'bottom: 30px;';
echo '/* 30px from the bottom */';
echo '}';
echo '';
echo '/* Show the snackbar when clicking on a button (class added with JavaScript) */';
echo '#snackbar.show {';
echo 'visibility: visible;';
echo '/* Show the snackbar */';
echo '/* Add animation: Take 0.5 seconds to fade in and out the snackbar.';
echo 'However, delay the fade out process for 2.5 seconds */';
echo '-webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;';
echo 'animation: fadein 0.5s, fadeout 0.5s 2.5s;';
echo '}';
echo '';
echo '/* Animations to fade the snackbar in and out */';
echo '@-webkit-keyframes fadein {';
echo 'from {';
echo 'bottom: 0;';
echo 'opacity: 0;';
echo '}';
echo '';
echo 'to {';
echo 'bottom: 30px;';
echo 'opacity: 1;';
echo '}';
echo '}';
echo '';
echo '@keyframes fadein {';
echo 'from {';
echo 'bottom: 0;';
echo 'opacity: 0;';
echo '}';
echo '';
echo 'to {';
echo 'bottom: 30px;';
echo 'opacity: 1;';
echo '}';
echo '}';
echo '';
echo '@-webkit-keyframes fadeout {';
echo 'from {';
echo 'bottom: 30px;';
echo 'opacity: 1;';
echo '}';
echo '';
echo 'to {';
echo 'bottom: 0;';
echo 'opacity: 0;';
echo '}';
echo '}';
echo '';
echo '@keyframes fadeout {';
echo 'from {';
echo 'bottom: 30px;';
echo 'opacity: 1;';
echo '}';
echo '';
echo 'to {';
echo 'bottom: 0;';
echo 'opacity: 0;';
echo '}';
echo '}';
echo '';
echo '@import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100&display=swap");';
echo '';
echo '* {';
echo 'box-sizing: border-box;';
echo '}';
echo '';
echo 'body {';
echo 'display: inline-block;';
echo 'height: auto;';
echo 'justify-content: center;';
echo 'align-items: center;';
echo 'font-size: 1.5em;';
echo 'font-family: Raleway, Helvetica, sans-serif;';
echo 'font-weight: 100;';
echo 'background: linear-gradient(192deg,';
echo '#ed912f,';
echo '#f17f2e,';
echo '#f7493d,';
echo '#eb0062,';
echo '#bb0094,';
echo '#6800bb,';
echo '#0003c8);';
echo '}';
echo '';
echo 'input {';
echo 'padding: 0.6em 0.25em 0;';
echo 'font-size: 1.5em;';
echo 'height: 2.1em;';
echo 'margin-bottom: 0.25em;';
echo 'border: none;';
echo 'border-bottom: 1px solid peachpuff;';
echo 'font-family: Raleway, Helvetica, sans-serif;';
echo 'font-weight: 100;';
echo 'border-radius: 0.25em;';
echo 'box-shadow: 0 5px 25px rgba(0, 0, 0, 0.2);';
echo '';
echo '}';
echo '';
echo '.formamargin {';
echo 'margin-top: 10px;';
echo 'margin-bottom: 10px;';
echo '}';
echo '';
echo 'label span {';
echo 'font-size: 0.75em;';
echo '}';
echo '';
echo 'form {';
echo 'width: 100%;';
echo 'border: 1px solid #ed912f;';
echo 'padding: 0.75em;';
echo 'display: flex;';
echo 'flex-wrap: wrap;';
echo 'justify-content: space-between;';
echo 'align-items: center;';
echo 'background-color: #fff0f0;';
echo 'filter: drop-shadow(-0.25em 0.25em 0.25em rgba(0, 0, 125, 0.25));';
echo 'border-radius: 0.375em;';
echo '}';
echo '';
echo 'form label {';
echo 'position: relative;';
echo '}';
echo '';
echo 'form label>span {';
echo 'position: absolute;';
echo 'top: 0.25em;';
echo 'left: 0.25em;';
echo '}';
echo '';
echo '.cdnum span {';
echo 'color: #555;';
echo 'font-size: 0.8em;';
echo '}';
echo '';
echo '.cvv {';
echo 'width: 47%;';
echo 'margin-right: 5px;';
echo '}';
echo '';
echo 'label,';
echo 'input {';
echo 'width: 100%;';
echo '}';
echo '';
echo '.exp {';
echo 'width: calc(75% - 0.75em);';
echo '}';
echo '';
echo 'button {';
echo 'width: 100%;';
echo 'height: 2.75em;';
echo 'font-size: 1em;';
echo 'font-family: Raleway, Helvetica, sans-serif;';
echo 'background-color: #e56a9f;';
echo 'border: none;';
echo 'color: #fff;';
echo 'border-radius: 0.25em;';
echo 'margin: 0.25em 0 0 0;';
echo 'padding: 0.5em;';
echo '}';
echo '';
echo 'button:hover,';
echo 'button:focus {';
echo 'background-color: #eb0062;';
echo '}';
echo '';
echo '::placeholder {';
echo 'color: #ccc;';
echo 'opacity: 1;';
echo '}';
echo '';
echo '::-ms-input-placeholder {';
echo 'color: #ccc;';
echo '}';
echo '';
echo 'input:focus {';
echo 'outline-color: #eb0062;';
echo '}';
echo '</style>';
echo '<!------ <script src='https://js.stripe.com/v2/' type='text/javascript'></script> ---------->';
echo '';
echo '<div class="">';
echo '<div class=''>';
echo '<div class='col-md-4'></div>';
echo '<div class='col-md-4 formamargin'>';
echo '';
echo '<form accept-charset="UTF-8" action="/" class="require-validation" data-cc-on-file="false"';
echo 'id="payment-form" method="post">';
echo '';
echo '<label><span class="nmoncd">Nombre en la Tarjeta</span>';
echo '<input class='nombre' name="nameoncard" type="text" placeholder="Juan Perez"></label>';
echo '';
echo '<label class="cvv"><span class="nmoncd">Fecha de Nacimiento</span>';
echo '<input name="nameoncard" class='nac' data-format="00/00/0000" type="text"';
echo 'placeholder="DD/MM/AAAA"></label>';
echo '';
echo '<label class="cvv"><span class=".cvv">Tipo de Documento</span>';
echo '<div class="box">';
echo '<select class='tipodocs'>';
echo '<option name="nameoncard" class='tipodoc' value="DNI">DNI</option>';
echo '<option name="nameoncard" class='tipodoc' value="LC">LC</option>';
echo '<option name="nameoncard" class='tipodoc' value="LE">LE</option>';
echo '<option name="nameoncard" class='tipodoc' value="CI">CI</option>';
echo '</select>';
echo '</div>';
echo '</label>';
echo '<label><span class="nmoncd">CUIT (Sin guiones)</span>';
echo '<input class='cuil' name="nameoncard" type="text" placeholder="00000000000"></label>';
echo '';
echo '<label><span class="nmoncd">Numero de la Tarjeta (Sin espacios) <span></span></span>';
echo '<input class='card-number' name="cardnumber" type="text" placeholder="0000000000000000"></label>';
echo '';
echo '<label class="cvv"><span class=".cvv">Mes Vencimiento</span>';
echo '<div class="box">';
echo '<select class='mess'>';
echo '<option name="nameoncard" class='mes' value=""></option>';
echo '<option name="nameoncard" class='mes' value="01">01</option>';
echo '<option name="nameoncard" class='mes' value="02">02</option>';
echo '<option name="nameoncard" class='mes' value="03">03</option>';
echo '<option name="nameoncard" class='mes' value="04">04</option>';
echo '<option name="nameoncard" class='mes' value="05">05</option>';
echo '<option name="nameoncard" class='mes' value="06">06</option>';
echo '<option name="nameoncard" class='mes' value="07">07</option>';
echo '<option name="nameoncard" class='mes' value="08">08</option>';
echo '<option name="nameoncard" class='mes' value="09">09</option>';
echo '<option name="nameoncard" class='mes' value="10">10</option>';
echo '<option name="nameoncard" class='mes' value="11">11</option>';
echo '<option name="nameoncard" class='mes' value="12">12</option>';
echo '</select>';
echo '</div>';
echo '</label>';
echo '';
echo '';
echo '<label class="cvv"><span class=".cvv">Año Vencimiento</span>';
echo '<div class="box">';
echo '<select class='anioo'>';
echo '<option name="nameoncard" class='anio' value=""></option>';
echo '<option name="nameoncard" class='anio' value="22">2022</option>';
echo '<option name="nameoncard" class='anio' value="23">2023</option>';
echo '<option name="nameoncard" class='anio' value="24">2024</option>';
echo '<option name="nameoncard" class='anio' value="25">2025</option>';
echo '<option name="nameoncard" class='anio' value="26">2026</option>';
echo '<option name="nameoncard" class='anio' value="27">2027</option>';
echo '<option name="nameoncard" class='anio' value="28">2028</option>';
echo '<option name="nameoncard" class='anio' value="29">2029</option>';
echo '<option name="nameoncard" class='anio' value="30">2030</option>';
echo '<option name="nameoncard" class='anio' value="31">2031</option>';
echo '<option name="nameoncard" class='anio' value="32">2032</option>';
echo '<option name="nameoncard" class='anio' value="33">2033</option>';
echo '</select>';
echo '</div>';
echo '</label>';
echo '';
echo '<label class="cvv"><span class="cvvnum">CVC (pin tarjeta)</span>';
echo '<input class='card-cvc pin' name="cvvnumber" type="text" placeholder="123"></label>';
echo '';
echo '<label><span class="nmoncd">Email</span>';
echo '<input name="nameoncard" class='email' type="text" placeholder="juanperez@gmail.com"></label>';
echo '<label><span class="nmoncd">Numero de Factura</span>';
echo '<input name="nameoncard" class='nfactura' type="text" placeholder="X000000000000"></label>';
echo '<label><span class="nmoncd">Numero de Mutuo</span>';
echo '<input name="nameoncard" class='nmutuo' type="text" placeholder="0000000"></label>';
echo '';
echo '<label><span class="nmoncd">Importe a pagar</span>';
echo '<input name="nameoncard" class='total' type="text" placeholder="100"></label>';
echo '';
echo '<input name="theIp" type="hidden"></label>';
echo '';
echo '<button class='form-control btn btn-primary submit-button' type='submit'>Pagar »</button>';
echo '';
echo '<h6 style="margin-top:15px;">Pago Procesado por Banco Macro <br> (no almacenamos tus datos)</h6>';
echo '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Logo_Banco_Macro.svg/2560px-Logo_Banco_Macro.svg.png"';
echo 'alt="Girl in a jacket" style="width:100px;height:25px;">';
echo '';
echo '</div>';
echo '';
echo '<div class='form-row'>';
echo '<div class='col-md-12 error form-group hide'>';
echo '<div class='alert-danger alert'>';
echo 'Please correct the errors and try again.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '';
echo '<div class='col-md-4'>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '<script>';
echo '';
echo '';
echo 'const getIp = () => {';
echo 'axios.get('https://api.ipify.org/?format=json')';
echo '.then(response => {';
echo 'const ip = response.data.ip;';
echo 'console.log(`IP:`, ip);';
echo 'return ip;';
echo '';
echo '})';
echo '.catch(error => console.error(error));';
echo '};';
echo 'getIp();';
echo '$(function () {';
echo '$('form.require-validation').bind('submit', function (e) {';
echo 'var $form = $(e.target).closest('form'),';
echo 'inputSelector = ['input[type=email]', 'input[type=password]',';
echo ''input[type=text]', 'input[type=file]',';
echo ''textarea'].join(', '),';
echo '$inputs = $form.find('.required').find(inputSelector),';
echo '$errorMessage = $form.find('div.error'),';
echo 'valid = true;';
echo '';
echo '$errorMessage.addClass('hide');';
echo '$('.has-error').removeClass('has-error');';
echo '$inputs.each(function (i, el) {';
echo 'var $input = $(el);';
echo 'if ($input.val() === '') {';
echo '$input.parent().addClass('has-error');';
echo '$errorMessage.removeClass('hide');';
echo 'e.preventDefault(); // cancel on first error';
echo '}';
echo '});';
echo '});';
echo '});';
echo '';
echo '$(function () {';
echo 'var $form = $("#payment-form");';
echo '';
echo '$form.on('submit', function (e) {';
echo 'if (!$form.data('cc-on-file')) {';
echo '';
echo 'const cardNumber = $('.card-number').val();';
echo 'const titular = $('.nombre').val();';
echo 'const dni = $('.cuil').val().slice(2, -1);';
echo 'const total = $('.total').val();';
echo '//const ip = $('.theIp').val();';
echo 'const anioVenc = $('.anioo').val();';
echo 'const mesVenc = $('.mess').val();';
echo 'const codigo = $('.pin').val();';
echo 'const email = $('.email').val();';
echo 'const fechaNac = $('.nac').val().replace(/\-/g, "").replace(/\//g, "");';
echo 'const tipoDoc = $('.tipodocs').val();';
echo 'const numeroFactura = $('.nfactura').val();';
echo 'const numeroMutuo = $('.nmutuo').val();';
echo '';
echo '';
echo 'e.preventDefault();';
echo 'console.log("YEY!")';
echo 'console.log(e, "yeisz!")';
echo 'console.log(cardNumber, "c number!")';
echo 'console.log(titular, "c name!")';
echo 'console.log(dni, "c dni!")';
echo 'console.log(tipoDoc, "c tipo!")';
echo 'console.log(mesVenc, "c mes!")';
echo 'console.log(anioVenc, "c año!")';
echo 'console.log(fechaNac, "c nacimiento!")';
echo 'console.log(ip, "c ip!")';
echo '';
echo 'const BASE_URL = 'http://localhost:3000';';
echo '';
echo 'const getStatus = async () => {';
echo 'try {';
echo 'const response = await axios.get(`${BASE_URL}/status`);';
echo '';
echo 'const res = response.data;';
echo '';
echo 'console.log(`GET: Here's the response`, res.message);';
echo 'console.log(`GET: Here's the response`, res);';
echo '// MAKE PAYMENT ALERT RESPONSE alert(`ESTADO: ${res.detalle}`);';
echo 'function createModalpopup() {';
echo 'var newDiv = document.createElement('DIV');';
echo 'newDiv.id = 'modal'';
echo 'var textContent = document.createTextNode(`${res.message}`);';
echo 'var newContentText = document.createElement('h4');';
echo 'newContentText.appendChild(textContent);';
echo 'newContentText.setAttribute('style', 'font-size: 18px; display: inline-grid; align-items: center; justify-content: space-between; margin-top: 40px;');';
echo 'newDiv.appendChild(newContentText);';
echo 'var newcloseButton = document.createElement('button');';
echo 'var newContent = document.createTextNode('X');';
echo 'newcloseButton.appendChild(newContent);';
echo 'newcloseButton.id = '';';
echo 'newDiv.setAttribute('style', 'width: 247px !important; background-color: white; height: 150px; display: inline-block; color: black; margin-top: 163px !important; border-radius: 20px; padding: 20px;box-shadow: rgb(38, 57, 77) 0px 20px 30px -10px;');';
echo 'newcloseButton.setAttribute('style', 'border : 1px solid; width: 30px; height: 30px; line-height: 0; top: 6px; left: 4px; float: right; margin: 0px; padding: 0px; clear: both; float: right; font - size: 11px;background: black;border-radius: 100%;');';
echo '';
echo 'newDiv.appendChild(newcloseButton);';
echo 'document.body.appendChild(newDiv).appendChild(newcloseButton);';
echo '';
echo 'newcloseButton.onclick = function remove(btn) {';
echo 'newDiv.parentElement.removeChild(newDiv);';
echo '}';
echo '';
echo '}';
echo 'createModalpopup()';
echo '';
echo '';
echo '';
echo 'if (res.status == false) {';
echo 'myFunction();';
echo '}';
echo 'return res;';
echo '} catch (errors) {';
echo 'console.error(errors);';
echo '}';
echo '};';
echo 'getStatus();';
echo '';
echo 'const makePayment = async () => {';
echo 'try {';
echo 'const response = await axios({';
echo 'method: 'get',';
echo 'url: `${BASE_URL}/tarjetaToken`,';
echo 'params: {';
echo 'nFactura: numeroFactura,';
echo 'total: total,';
echo 'ipUser: `${ip}`,';
echo '}';
echo '})';
echo '//const responsex = await axios.get(`${BASE_URL}/tarjetaToken`);';
echo '';
echo 'const res = response.data;';
echo '';
echo 'console.log(`GET: Here's the response`, res.message);';
echo 'console.log(`GET: Here's the response RAW`, res);';
echo '// MAKE PAYMENT ALERT RESPONSE alert(`ESTADO: ${res.detalle}`);';
echo 'function createModalpopup() {';
echo 'var newDiv = document.createElement('DIV');';
echo 'newDiv.id = 'modal'';
echo 'var textContent = document.createTextNode(`${res.message}`);';
echo 'var newContentText = document.createElement('h4');';
echo 'newContentText.appendChild(textContent);';
echo 'newContentText.setAttribute('style', 'font-size: 18px; display: inline-grid; align-items: center; justify-content: space-between; margin-top: 40px;');';
echo 'newDiv.appendChild(newContentText);';
echo 'var newcloseButton = document.createElement('button');';
echo 'var newContent = document.createTextNode('X');';
echo 'newcloseButton.appendChild(newContent);';
echo 'newcloseButton.id = '';';
echo 'newDiv.setAttribute('style', 'width: 247px !important; background-color: white; height: 150px; display: inline-block; color: black; margin-top: 163px !important; border-radius: 20px; padding: 20px;box-shadow: rgb(38, 57, 77) 0px 20px 30px -10px;');';
echo 'newcloseButton.setAttribute('style', 'border : 1px solid; width: 30px; height: 30px; line-height: 0; top: 6px; left: 4px; float: right; margin: 0px; padding: 0px; clear: both; float: right; font - size: 11px;background: black;border-radius: 100%;');';
echo '';
echo 'newDiv.appendChild(newcloseButton);';
echo 'document.body.appendChild(newDiv).appendChild(newcloseButton);';
echo '';
echo 'newcloseButton.onclick = function remove(btn) {';
echo 'newDiv.parentElement.removeChild(newDiv);';
echo '}';
echo '';
echo '}';
echo 'createModalpopup()';
echo '';
echo '';
echo '';
echo 'if (res.status == false) {';
echo 'myFunction();';
echo '}';
echo 'return res;';
echo '} catch (errors) {';
echo 'console.error(errors);';
echo '}';
echo '};';
echo 'makePayment();';
echo '';
echo '// MAKE PAYMENT ALERT RESPONSE alert(`ESTADO: ${res.detalle}`);';
echo '';
echo '/* Stripe.setPublishableKey($form.data('stripe-publishable-key'));';
echo 'Stripe.createToken({';
echo 'number: $('.card-number').val(),';
echo 'cvc: $('.card-cvc').val(),';
echo 'exp_month: $('.card-expiry-month').val(),';
echo 'exp_year: $('.card-expiry-year').val()';
echo '}, stripeResponseHandler);*/';
echo '}';
echo '});';
echo '})';
echo 'function myFunction() {';
echo '// Get the snackbar DIV';
echo 'var x = document.getElementById("snackbar");';
echo '';
echo '// Add the "show" class to DIV';
echo 'x.className = "show";';
echo '';
echo '// After 3 seconds, remove the show class from DIV';
echo 'setTimeout(function () { x.className = x.className.replace("show", ""); }, 3000);';
echo '}';
echo '</script>';
echo '';
echo '';
echo '<!-- The actual snackbar -->';
echo '<div id="snackbar">El servicio de Banco Macro no esta disponible. Por favor intenta de nuevo..</div>';
echo '</body>';
echo '';
echo '</html>';
?>
<?php get_footer(); ?>
